### PR TITLE
Improve startup time by speeding up internal block sync

### PR DESCRIPTION
**Pull request by netoneko**
## Description

This fix speeds up internal block sync process by processing batches of blocks.

Batch size is configurable as well.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/orbs-network/orbs-contributor-guide/blob/master/CONTRIBUTING.md) doc
- [ ] I have opened an issue and discussed the solution suggested in this PR
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by electricmonk** [comment]
@netoneko was there any discussion of this feature and the problem it solves prior to submitting this PR?

**Comment by netoneko** [comment]
@electricmonk yes, I discussed this with @ronnno, who is the maintainer of block storage and internal block sync.

**Comment by electricmonk** [comment]
Can you please review the changes with @gadcl and/or @OdedWx ?

**Comment by netoneko** [comment]
I don't think the changes are significant enough to warrant such a review, there was no change in the architecture, I was only capitalizing on top of existing code.

Some numbers: with a file of 9.5M blocks, 2.8Gb in size (vchain 1M that @IdoZilberberg uses to test performance in production).

* batch size of 1: 3m31s
* batch size of 1k: 3m14s
* batch size of 10k: 2m50s

I am sure the difference will only become more pronounced in the future.

**Comment by electricmonk** [comment]
This might affect timings and result in races. A review is needed.

Furthermore, what am I missing? You’re improving by less than 20%

Shai

________________________________

**Comment by OdedWx** [comment]
@gadcl will the LeanHelix refactor address it without batching ?
(should reduce the time spent on acknowledge)

**Pull request closed without merging**
