### PR TITLE
Patch/merge v1.1.1

### PR DESCRIPTION
**Pull request by ronnno**
Merged release/v1.1.0 branch into master. resulting changes involve mostly lean-helix, i assume the other changes were manually copied previously. @IdoZilberberg please review?

### CODE REVIEW

**Comment by electricmonk** [comment]
I thought every change to 1.1.x were also applied to master. What wasn’t?

**Comment by IdoZilberberg** [comment]
@ronnno What is the high level description of these changes? I see one function call was moved, and several other function calls replaced with another function.

**Comment by IdoZilberberg** [comment]
> I thought every change to 1.1.x were also applied to master. What wasn’t?

it wasnt

**Comment by IdoZilberberg** [comment]
> @ronnno What is the high level description of these changes? I see one function call was moved, and several other function calls replaced with another function.

@ronnno: merged the currently deployed production version v1.1.1. it contains several fixes and enhancements.

**Comment by noambergIL** [comment]
Without this code the audit node doesn't run ...

**Pull request merged**
