### PR TITLE
Use our fork of ntp library

### PR DESCRIPTION
**Pull request by netoneko**
## Description

Uses our fork of NTP library; continues #1163

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/orbs-network/orbs-contributor-guide/blob/master/CONTRIBUTING.md) doc
- [ ] I have opened an issue and discussed the solution suggested in this PR
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

None

### CODE REVIEW

**Comment by electricmonk** [comment]
Why did we fork this library?

**Comment by netoneko** [comment]
We want to control all the source code for security reasons.

**Comment by electricmonk** [comment]
Did we fork all other dependencies? I don’t think we actually went forward with this. Is there anything specific in this lib that scares you?

Shai

________________________________

**Comment by netoneko** [comment]
@electricmonk the only dependency is `golang.org/x/net`, and I believe we can trust it.

**Comment by electricmonk** [comment]
Go-ethereum?

Shai

________________________________

**Comment by IdoZilberberg** [comment]
@netoneko The original ntp lib has BSD-2 license, not MIT. I think has no restrictions but before going forward with using a forked version of it you **must** consult legal to:
a) make sure using BSD-2 code does not prevent us from using MIT license, and in general does not create any constraints or obligations on us.
b) ask what to do about the license header we put in all the files - there is already the header of the original author.
@electricmonk

**Comment by netoneko** [comment]
@IdoZilberberg forking the library does not mean changing its license, only hosting it in our github account. Let's consult legal if we can link our code with bsd2 libs. My understanding is that we could do that.

**Pull request closed without merging**
