### PR TITLE
enforce network type field in blocks file header

### PR DESCRIPTION
**Pull request by ronnno**
## Description

Validate `NETWORK_TYPE` configuration value matches the value found in blocks file header, on filesystem block storage adapter init. Fail loading if values do not match.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/orbs-network/orbs-contributor-guide/blob/master/CONTRIBUTING.md) doc
- [ ] I have opened an issue and discussed the solution suggested in this PR
- [ ] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

Currently network type is not in use. production configurations use the reserved value 0.

### CODE REVIEW

**Comment by electricmonk** [comment]
WAIT
I’m under the assumption we decided to deprecate network type as a concept.

Shai

________________________________

**Comment by ronnno** [comment]
This is intended for cleanliness and consistency - and avoids the question of what will happen with this field in the future. as it currently exists, and since the header structure indicates it should have the configured value, and since the spec currently indicates that a vchain is identified by both network type and vchain id, it's a bug to ignore the value. 

if not to enforce it, the opposite alternative is to remove any reference to the config value in the file header: to rename the field to "reserved" and to override it with 0.

I prefer enforcing it because it will ensure that in the future if we replace this concept with something else we will address the questions of representation in the blocks file and of validation as part of a future refactor. 

@OdedWx which option do you prefer?

**Comment by electricmonk** [comment]
I don’t think we actually set this value anywhrre

Shai

________________________________

**Comment by ronnno** [comment]
the value itself is left 0 "reserved" in all deployments, some tests use "testnet" (particularly - consensus algorithm tests i believe) and the test I've added in this PR increments the value to 1 to check we detect mismatches.

**Comment by OdedWx** [comment]
I think that it makes more sense to compare it to teh configuration then read it and not do anything with.
The address.network_type should be deprecated. We may consider to add it to the header/transactions in future protocol revisions as a mean of convenience.

**Pull request merged**
